import React, { useEffect, useRef, useState } from 'react';
import { useShipAIStore } from '../../store/useShipAIStore';
import hljs from 'highlight.js';
import 'highlight.js/styles/atom-one-dark.css';
import { Copy, Check, BookOpen } from 'lucide-react';

export const FileViewer: React.FC = () => {
  const { selectedFile, configJson, fileTree } = useShipAIStore();
  const codeRef = useRef<HTMLElement>(null);
  const [copied, setCopied] = useState(false);
  const [content, setContent] = useState<string>('// Select a file to view its contents\n// Real contents would be fetched from the backend');

  const fileInfo = fileTree.find(f => f.path === selectedFile);

  useEffect(() => {
    // In a real app, we'd fetch the file content from the backend using the selectedFile path
    // For now, we show a mock string if a file is selected
    if (selectedFile) {
      setContent(`# Content of ${selectedFile}\n# Generated by ShipAI\n\ndef main():\n    print("Hello from ShipAI")\n`);
    } else {
      setContent('// Select a file to view its contents');
    }
  }, [selectedFile]);

  useEffect(() => {
    if (codeRef.current) {
      // remove highlight.js dataset attribute to force re-highlighting
      delete codeRef.current.dataset.highlighted;
      hljs.highlightElement(codeRef.current);
    }
  }, [content]);

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!selectedFile) {
    return (
      <div className="flex-1 bg-gray-950 flex flex-col items-center justify-center text-gray-600">
        <FileCode size={48} className="mb-4 opacity-20" />
        <p>No file selected</p>
      </div>
    );
  }

  // Derive citation if it's a key file
  let citation = null;
  if (fileInfo?.name === 'retriever.py') citation = configJson?.decisions?.search_type?.book;
  if (fileInfo?.name === 'reranker.py') citation = configJson?.decisions?.reranker?.book;
  if (fileInfo?.name === 'pii_guard.py') citation = configJson?.decisions?.pii?.book;

  return (
    <div className="flex-1 flex flex-col bg-gray-950 relative overflow-hidden">
      {/* Header bar */}
      <div className="h-10 border-b border-gray-800 bg-gray-900 flex items-center justify-between px-4 shrink-0">
        <div className="text-sm text-gray-300 font-medium truncate pr-4">
          {fileInfo?.name || selectedFile.split(/[/\\]/).pop()}
        </div>
        <div className="flex items-center gap-2">
          {citation && (
            <div className="group relative">
              <button className="text-xs text-blue-400 hover:text-blue-300 flex items-center gap-1 bg-blue-900/30 px-2 py-1 rounded">
                <BookOpen size={12} />
                <span>Why?</span>
              </button>
              {/* Tooltip */}
              <div className="absolute right-0 top-full mt-1 w-64 p-2 bg-gray-800 border border-gray-700 rounded shadow-xl opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-50 text-xs text-gray-200 leading-relaxed">
                <span className="font-semibold text-blue-400 block mb-1">Architecture Decision</span>
                Based on: <em className="text-gray-400">{citation}</em>
              </div>
            </div>
          )}
          <button onClick={handleCopy} className="text-gray-400 hover:text-white transition-colors" title="Copy code">
            {copied ? <Check size={16} className="text-green-500" /> : <Copy size={16} />}
          </button>
        </div>
      </div>
      
      {/* Code Area */}
      <div className="flex-1 overflow-auto custom-scrollbar bg-gray-950 p-4">
        <pre className="m-0 text-sm">
          <code ref={codeRef} className="language-python bg-transparent">
            {content}
          </code>
        </pre>
      </div>
    </div>
  );
};

// Also need FileCode here since it's used in empty state
import { FileCode } from 'lucide-react';
